openapi: 3.0.1
info:
    title: Sumly
    description: Summarises content from a text or a URL.
    version: "v1"
servers:
    - url: http://localhost:3000
paths:
    /url:
        get:
            operationId: getUrl
            summary: Summarises text retrieved from the given URL.
            parameters:
                - in: query
                  name: query
                  schema:
                      type: string
                  description: Summarises text retrieved from the given URL.
            responses:
                "200":
                    description: OK
    /text:
        get:
            operationId: getText
            summary: Summarises text from the content.
            parameters:
              - in: query
                name: search
                schema:
                  type: string
                description: Summarises text from the content.
            responses:
                "200":
                    description: OK